config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # DEVELOPMENT
  resources :devpages, only: :show
  
  devise_for :users, controllers: {
    # sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations'
  }
  
  get 'venues/new/venue_search', to: 'venues#venue_search'
  get '/location_search', to: 'pages#home'

  
  root to: 'pages#home'
  resources :venues do
    resources :reviews, only: [:index, :create, :new, :edit, :update, :destroy] do
      resources :photos, only: [:destroy]
    end
    resources :photos, only: [:destroy]
    get 'venue_search', on: :new
  end

  resources :cities, only: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/venue.rb
class Venue < ApplicationRecord
  # belongs_to :user
  belongs_to :city, optional: true
  has_many :reviews, dependent: :destroy
  # belongs_to :owner, class_name: 'User', optional: true
  has_one :cover_photo, dependent: :destroy
  has_and_belongs_to_many :categories
  has_many :opening_hours
  has_one :feature_set
  has_one :address, dependent: :destroy
  has_many :photos, as: :imageable, dependent: :destroy
  has_many :venue_users, dependent: :destroy
  has_many :users, through: :venue_users
  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :photos

  validates :foursquare_id, uniqueness: true, allow_blank: true
  validates :name, presence: true
  # validates :address, presence: true
  validates_uniqueness_of :name, scope: :user_id
  # validates :description, length: { maximum: 68 }, allow_blank: true
  
  # scope :location, -> location { near(location) }
  scope :location, -> location {  where(id: Address.near(location).joins(:venue).preload(:venue).map(&:venue).map(&:id)) }
  scope :location_with_distance, -> location, distance {  where(id: Address.near(location, distance).joins(:venue).preload(:venue).map(&:venue).map(&:id)) }
  scope :rating, -> number { where("rating >= ?", number) }
  scope :upload_speed, -> number { where("round(upload_speed) >= ?", number.to_i) if number.to_i > 0 }
  scope :serves_food, -> { where(serves_food: true) }
  scope :air_conditioning, -> { where(air_conditioning: true) }
  scope :comfort, -> number { where("comfort >= ?", number) }
  scope :quietness, -> number { where("quietness >= ?", number) }
  scope :plug_sockets, -> number { where("plug_sockets >= ?", number) }
  scope :has_wifi, -> { where(has_wifi: true) }
  scope :no_wifi_restrictions, -> hours { where("wifi_restrictions < ?", hours) if hours > "0" }
  scope :has_upload_speed_data, -> { where.not(upload_speed: nil) }

  def update_values(
      review,
      attributes_to_average = [],
      attribues_to_truth_check = [],
      averaged_values = {},
      truth_checked_values = {}
    )

    # Sort attributes into seperate arrays for averaging or truth checking
    review.attributes.each do |k, val|
      attributes_to_average << k if attr_is_averageable?(k) && val != nil
      attribues_to_truth_check << [k,val] if attr_is_boolean?(k) && val != nil
    end
    
    # Recalculate averages for all averageable values which were present in review
    attributes_to_average.each do |attribute|
      averaged_values[attribute] = calculate_average(attribute)
    end

    # Assign new true/false value if the value passes truth checking
    attribues_to_truth_check.each do |boolean_key_value_pair|
      k, val = boolean_key_value_pair[0], boolean_key_value_pair[1]
      truth_checked_values[k] = truth_checked_val(k, val)
    end
    
    # Merge hashes of values to update
    updated_values = averaged_values.merge(truth_checked_values)

    # Update values
    update(updated_values)
  end

  # def to_param
  #   "#{to_global_id.to_param}-#{name.parameterize}"
  # end

  def all_photos(combined_images = [])
    photos.map { |photo| combined_images << photo }
    reviews.map { |review| review.photos.map { |photo| combined_images << photo } }
    combined_images
  end

  def featured_photo
    all_photos.find { |photo| photo.featured }
  end

  private

  def attr_is_averageable?(k)
    averageable_values = ["rating", "plug_sockets", "comfort", "quietness", "upload_speed", "download_speed", "ping"]
    averageable_values.include?(k) ? true : false
  end

  def attr_is_boolean?(k)
    boolean_values = ["serves_food", "air_conditioning", "has_wifi"]
    boolean_values.include?(k) ? true : false
  end

  def calculate_average(attribute)
    self.reviews.average(attribute.to_sym)
  end

  def truth_checked_val(attribute, value)
    # self.reviews.reload
    if self.reviews.count == 0
      nil
    # executes if there is only one review, or the last review value matches current
    elsif self.reviews.count == 1 || self.reviews[-2].send(attribute) == value
      value
    else
      # returns the previous value if it does not match the current
      self.reviews[-2].send(attribute)
    end
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  include Foursquare
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  before_action :set_venues, only: [:index]
  before_action :set_venue, only: [:show, :edit, :update, :destroy]
  before_action :venues_params, only: [:index]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user, only: [:edit, :update, :destroy]
  # @venue should be called as venue for decorated instance in views
  decorates_assigned :venue
  decorates_assigned :review
  # has_scope :location, if: :location_given?, unless: :distance_given?
  has_scope :rating
  has_scope :upload_speed
  has_scope :no_wifi_restrictions
  has_scope :comfort
  has_scope :quietness
  has_scope :plug_sockets
  has_scope :has_wifi, type: :boolean
  respond_to :html, :json
  
  def index
    # checks if venues exist for location and redirects if not
    venues_in_searched_location = @venues.location(venues_params[:location]) if location_given?
    redirect_to cities_path and return if !venues_in_searched_location.present?

    # Applies scopes
    @venues = apply_scopes(venues_in_searched_location).all
    @venues = @venues.location_with_distance(venues_params[:location], venues_params[:distance].to_i) if location_given? && distance_given?
    # @venues = @venues.near(venues_params[:location], venues_params[:distance]) if location_given? && distance_given?

    order_venues_by_param(@venues, venues_params[:order_by]) if venues_params[:order_by]

    if !request.xhr?
      set_map_markers(@venues) unless params[:order_by] 
      respond_with(@venues)
    end
  end

  def show
    @review = Review.new
    set_map_markers(@venue)
  end

  def new
    # @opening_hours = OpeningHour.new
    # @opening_hours = []
    # 7.times do
    #   @opening_hours << OpeningHour.new
    # end
    # @weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
  end

  def create
    @venue = Venue.new(venue_params)
    @address = Address.new(venue_address_params.merge(venue: @venue))
    @venue.users << current_user
    if @venue.save && @address.save
      save_photo_if_photo_uploaded(venue: @venue)
      begin
        VenueMailer.new_venue_listed(user: current_user, venue: @venue).deliver_now!
        flash[:success] = "Thank you, #{@venue.name} was successfully listed."
      rescue StandardError => e
        flash[:alert] = "#{@venue.name} was listed, but there was a problem sending an email confirmation. Please check your email."
      end
      redirect_to venue_path(@venue)
    else
      @venue.errors.messages.merge(@address.errors.messages).each_pair do |key, value|
        flash[:error] = "#{key.capitalize} #{value[0]}."
      end
      render :new
    end

    # create new opening_hour_set and assign venue
    # @opening_hour_set = OpeningHourSet.new
    # @opening_hour_set.venue = @venue
    # @opening_hour_set.save!

    # save all opening_hours and assign to opening_hour_set
    # unless opening_hours_params.empty?
    #   opening_hours_params[:opening_hour].each do |hours|
    #     new_opening_hours = OpeningHour.new(hours)
    #     new_opening_hours.opening_hour_set = @opening_hour_set
    #     new_opening_hours.save!
    #   end
    # end
  end

  def edit
  end

  def update
    @venue.address.update(venue_address_params) if params[:venue][:address_attributes].present?
    if @venue.update(venue_params)
      save_photo_if_photo_uploaded(venue: @venue)
      redirect_to venue_path(@venue)
    else
      render :edit
    end
  end

  def destroy
    redirect_to venues_path if @venue.destroy
  end

  def venue_search
    location = venue_search_params[:location]
    search = venue_search_params[:query]
    url = api_call(search, location)
    response = open(url).read
    @response_json = JSON.parse(response)
    render json: @response_json
  end

  private

  def set_venue
    @venue = Venue.find(params[:id])
  end

  def set_venues
    @venues = Venue.all
  end

  def venues_params
    params.permit(
      :location,
      :rating,
      :upload_speed,
      :comfort,
      :plug_sockets,
      :quietness,
      :has_wifi,
      :order_by,
      :distance,
      :no_wifi_restrictions,
    )
  end

  def venue_params
    params.require(:venue).permit(
      :name,
      :description,
      :serves_food,
      :air_conditioning,
      :wifi_restrictions,
      :has_wifi,
      :foursquare_id
    )
  end

  def venue_address_params
    params.require(:venue).require(:address_attributes).permit(
      :address,
      :city,
      :postcode,
      :country,
      :longitude,
      :latitude,
    )
  end

  def new_venue_photo_params
    params[:venue][:photo]
  end

  def venues_boolean_params
    params.permit(
      :serves_food,
      :air_conditioning,
      :wifi_restrictions,
      :no_wifi_restrictions,
      :has_wifi
    )
  end

  def save_photo_if_photo_uploaded(venue:)
    if new_venue_photo_params
      @photo = Photo.new(imageable: venue)
      @photo.image.attach(new_venue_photo_params[:image])
      @photo.save
    end
  end

  # def opening_hours_params
  #   # params.require([:venue, :opening_hour]).permit(:day, :open, :close)
  #   params.require(:venue).permit(opening_hour: [:day, :open, :close])
  # end

  def venue_search_params
    params.permit(:query, :location)
  end

  def set_map_markers(venues)
    @markers = []
    Array(venues).each do |venue|
      @markers << {
        lat: venue.address.latitude,
        lng: venue.address.longitude,
        infoWindow: render_to_string(partial: "venues/index_partials/index__map_cards", locals: { venue: venue })
      }
    end
  end

  def order_venues_by_param(venues, param)
    @venues = @venues.reorder("#{param} DESC NULLS LAST")
  end

  def location_given?
    venues_params[:location] && venues_params[:location] != "" && venues_params[:location] != "Everywhere"
  end

  def query_given?
    venues_params[:location] && venues_params[:location] != ""
  end

  def distance_given?
    venues_params[:distance] && venues_params[:distance].to_i > 0
  end
  
  def authorize_user
    authorize @venue
  end

  def user_not_authorized(exception)
    policy_name = exception.policy.class.to_s.underscore
 
    flash[:error] = t "#{policy_name}.#{exception.query}", scope: "pundit", default: :default

    redirect_to(venue_path(@venue))
  end
end

app/helpers/venues_helper.rb
module VenuesHelper

  def searched_location(location)
    if location && location.length > 0
      location[0] == location[0].upcase ? location : location.capitalize
    else
      "Everywhere"
    end
  end

  def average_wifi_speed(location, wifi_speeds = [])
    if location && location.length > 0
      full_results_for_location(location).each do |venue|
        wifi_speeds << venue.upload_speed if !venue.upload_speed.nil?
      end
      wifi_speeds.empty? ? "No wifi speed data" : "#{calculate_average_wifi_speed(wifi_speeds)} Mbps"
    elsif location.nil? || location == "Everywhere"
      Venue.all.each do |venue|
        wifi_speeds << venue.upload_speed if !venue.upload_speed.nil?
      end
      wifi_speeds.empty? ? "No wifi speed data" : "#{calculate_average_wifi_speed(wifi_speeds)} Mbps"
    else
      "Unknown"
    end
  end

  def total_listings_count(location)
    location && location.length > 0 ? full_results_for_location(location).count(:all) : Venue.all.count(:all)
  end

  def distance_options
    options_for_select([
      ["Distance", 0, { :data => { :target => 'set-selected-option.option', :selected => "#{params[:distance] == "0"}"}}],
      ["1 Kilometer", 1, { :data => { :target => 'set-selected-option.option', :selected => "#{params[:distance] == "1"}"}}],
      ["3 Kilometers", 3, { :data => { :target => 'set-selected-option.option', :selected => "#{params[:distance] == "3"}"}}],
      ["5 Kilometers", 5, { :data => { :target => 'set-selected-option.option', :selected => "#{params[:distance] == "5"}"}}],
      ["10 Kilometers", 10, { :data => { :target => 'set-selected-option.option', :selected => "#{params[:distance] == "10"}"}}],
    ])
  end

  def rating_options(rating_param, value)
    icon_element = content_tag( :i, nil, :class=>'fas fa-2x fas fa-star')
    span_element = content_tag( :span, icon_element, :class=>'icon is-medium has-text-light', :data => { :target => 'icon-state.icon' })
    label = label_tag( "#{rating_param}_#{value}", span_element, :class=>'c-rating-star--label', :data => { :action => 'click->icon-state#selectIcons' })
  end

  def feature_rating_options(feature_param, value)
    smile_icon = smile_type(value)
    icon_element = content_tag( :i, nil, :class=>"fas fa-2x fas fa-#{smile_icon}")
    span_element = content_tag( :span, icon_element, :class=>'icon is-medium has-text-light', :for => "#{feature_param}", :value => "#{value}", :data => { :target => 'icon-state.icon' })
    label_tag( "#{feature_param}_#{value}", span_element, :class=>'c-rating-star--label', :data => { :action => 'click->icon-state#selectIcons'})
  end

  def order_by_options
    options_for_select([
      ["Distance", { :data => { :url => "#{url_for(request.params.merge(:order_by => "distance"))}", :target => 'set-selected-option.option index-cards-ordering.option', :selected => "#{params[:order_by] == "distance"}"}}],
      ["Top rated", { :data => { :url => "#{url_for(request.params.merge(:order_by => "rating"))}", :target => 'set-selected-option.option index-cards-ordering.option', :selected => "#{params[:order_by] == "rating"}"}}],
      ["Wifi Speed", { :data => { :url => "#{url_for(request.params.merge(:order_by => "upload_speed"))}", :target => 'set-selected-option.option index-cards-ordering.option', :selected => "#{params[:order_by] == "upload_speed"}"}}],
      ["Price", { :data => { :url => "#{url_for(request.params.merge(:order_by => "price"))}", :target => 'set-selected-option.option index-cards-ordering.option', :selected => "#{params[:order_by] == "price"}"}}]
    ])
  end

  def highest_upload_speed(venues)
    if venues.length > 0 && at_least_one_value_exists(venues, "upload_speed")
      venues.reorder("upload_speed DESC NULLS LAST").first.upload_speed.ceil
    else
      0
    end
  end

  def lowest_upload_speed(venues)
    if venues.length > 0
      venues.reorder("upload_speed ASC NULLS LAST").first.upload_speed.ceil - 1
    else
      0
    end
  end

  def selected_upload_speed(venues, params_upload_speed)
    if venues.length > 0 && params_upload_speed
      params_upload_speed
    else
      0
    end
  end

  def wifi_restrictions_options
    [['Wifi Restrictions', 0], ['1 Hour', 1], ['2 Hours', 2], ['3 Hours', 3], ['4+ Hours', 4]]
  end

  private

  def smile_type(value)
    case value
    when 0
      "frown"
    when 1
      "meh"
    when 2
      "smile"
    end
  end

  def at_least_one_value_exists(venues, attribute)
    venues.any? {|venue| venue.send(attribute).is_a?(Float)}
  end

  def calculate_average_wifi_speed(wifi_speeds)
    (wifi_speeds.sum / wifi_speeds.length).round(2)
  end

  def full_results_for_location(location)
    Venue.location(location)
  end
end

app/views/venues/shared_partials/_map.erb
<div
  id="map"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  data-target="mobile-index-navigation.map">
</div>

app/views/venues/shared_partials/_venue_form.html.erb
<%= form_with model: venue, local: true do |venue_form| %>
  <section class="section" data-controller="venue-autofill">
    <div class="container">
      <div class="columns">
        <div class="column is-half is-offset-one-quarter">
        <%= venue.form_heading %>
          <div class="field c-field-has-autocomplete-results" data-controller="algolia-places">
            <label class="label">Location</label>
            <p class="control has-icons-left">
              <%= venue_form.text_field :location,
              class: "input", value: "#{venue.venue_city}", placeholder: "Search for a location...",
              :data => {
                :target => 'venue-autofill.locationInput algolia-places.addressInput',
                :action => 'keyup->algolia-places#changeHandler',
                :request_path => location_search_path
              } %>
              <span class="icon is-small is-left">
                <i class="fas fa-map-marker-alt"></i>
              </span>
            </p>
            <div class="c-autocomplete-results-container" data-target="algolia-places.resultsContainer"></div>
          </div>
          <div class="field c-field-has-autocomplete-results">
            <label class="label">Name</label>
            <div class="is-hidden" data-target="venue-autofill.path" data-url=<%= "#{venue_search_new_venue_path}" %>></div>
            <p class="control has-icons-left has-icons-right">
              <%= venue_form.text_field :name,
                autofocus: true,
                class: "input",
                placeholder: "What is the name of the venue?",
                :data => {
                  :target => 'venue-autofill.name',
                  :action => 'keyup->venue-autofill#searchHandler'
                }
              %>
              <span class="icon is-small is-left">
                <i class="fas fa-store-alt"></i>
              </span>
            </p>
            <div class="c-autocomplete-results-container" data-target="venue-autofill.results">
            </div>
          </div>

          <!-- ADDRESS -->
          <%= venue_form.fields_for :address, address do |address_form| %>
            <div class="field">
              <label class="label">Address</label>
              <p class="control has-icons-left">
                <%= address_form.text_field :address,
                  class: "input",
                  value: "#{address.address}",
                  placeholder: "What's the address?",
                  :data => {
                    :target => 'venue-autofill.address'
                  }
                %>
                <span class="icon is-small is-left">
                  <i class="fas fa-home"></i>
                </span>
              </p>
            </div>
            <div class="field">
              <label class="label">City</label>
              <p class="control has-icons-left">
                <%= address_form.text_field :city,
                  class: "input",
                  value: "#{address.city}",
                  :data => {
                    :target => 'venue-autofill.city'
                  }
                %>
                <span class="icon is-small is-left">
                  <i class="fas fa-city"></i>
                </span>
              </p>
            </div>
            <div class="field">
              <label class="label">Postcode</label>
              <p class="control has-icons-left">
                <%= address_form.text_field :postcode,
                  class: "input",
                  value: "#{address.postcode}",
                  :data => {
                    :target => 'venue-autofill.postcode'
                  }
                %>
                <span class="icon is-small is-left">
                  <i class="fas fa-paper-plane"></i>
                </span>
              </p>
            </div>
            <div class="field">
              <label class="label">Country</label>
              <p class="control has-icons-left">
                  <%= address_form.text_field :country,
                    class: "input",
                    value: "#{address.country}",
                    :data => {
                      :target => 'venue-autofill.country'
                    }
                  %>
                <span class="icon is-small is-left">
                  <i class="fas fa-globe-europe"></i>
                </span>
              </p>
            </div>
            <%= address_form.hidden_field :longitude, :data => { :target => 'venue-autofill.longitude' } %>
            <%= address_form.hidden_field :latitude, :data => { :target => 'venue-autofill.latitude' } %>
          <% end %>

          <!-- CATEGORY -->
          <div class="field">
            <label class="label">Category</label>
            <p class="control has-icons-left">
              <%= venue_form.text_field :category,
                class: "input",
                value: "#{venue.categories.first.try(:name)}",
                placeholder: "e.g. Café/Bar/Coworking Space",
                :data => {
                  :target => 'venue-autofill.category'
                } %>
              <span class="icon is-small is-left">
                <i class="fas fa-info-circle"></i>
              </span>
            </p>
          </div>
          <div class="field">
            <label class="label">Description</label>
            <p class="control has-icons-left">
              <%= venue_form.text_field :description,
              class: "input",
              placeholder: "e.g. Café/Bar/Coworking Space",
              :data => {
                :target => 'venue-autofill.description'
              } %>
              <span class="icon is-small is-left">
                <i class="fas fa-info-circle"></i>
              </span>
            </p>
          </div>

          <!-- WIFI -->
          <div class="field">
            <label class="label">Wifi</label>
            <div class="control">
              <label class="checkbox">
                <%= venue_form.check_box :has_wifi  %>
                This venue has WiFi
              </label>
            </div>
          </div>
          <div class="field">
            <div class="control is-expanded has-icons-left">
              <div class="select is-fullwidth">
                <!-- <select name="wifi_restrictions">
                  <%= wifi_restrictions_options %>
                </select> -->
                <%= venue_form.select(:wifi_restrictions, wifi_restrictions_options) %>
              </div>
              <div class="icon is-small is-left">
                <i class="fas fa-stopwatch"></i>
              </div>
            </div>
          </div>

          <!-- TAGS -->
          <label class="label">Please select appropriate tags</label>
          <div class="tags" data-controller="tags">
            <span class="tag u-pointer" data-action="click->tags#activateTag">
              Serves Food
            </span>
            <span class="tag u-pointer" data-action="click->tags#activateTag">
              Open late
            </span>
          </div>

          <!-- PHOTO DISPLAY -->
          <label class="label">Photos</label>
          <div class="columns is-multiline">
            <% if venue.photos.any? %>
              <% venue.photos.each do |photo| %>
                <div class="column is-one-third">
                  <figure class="image is-square c-photo-thumbnail">
                    <%= link_to "Delete", venue_photo_path(venue, photo), method: :delete, class: "delete delete-button" %>
                    <%= image_tag photo.image, class: "u-object-fit" %>
                  </figure>
                </div>
              <% end %>
            <% end %>
          </div>
          
          <!-- PHOTO UPLOAD -->
          <div class="field u-margin-t-10px" data-controller="photo-upload">
            <div class="file has-name is-boxed is-primary is-small is-centered">
              <label class="file-label">
                <%= venue_form.fields_for :photo, photo do |photo_form| %>
                  <%= photo_form.file_field :image, class: "file-input", placeholder: "John", data: { action: "photo-upload#handleChange", target: "photo-upload.photoUploadInput" } %>
                <% end %>
                <span class="file-cta">
                  <span class="file-icon">
                    <i class="fas fa-upload"></i>
                  </span>
                  <span class="file-label">Upload a photo</span>
                </span>
                <span class="file-name is-hidden" data-target="photo-upload.fileName"></span>
              </label>
            </div>
          </div>
          


          <div id="opening-hours" class="is-hidden">
            <%#= venue_form.label :opening_hours %>
            <%# @opening_hours.each_with_index do |opening_hour, i| %>
              <div class="form-row">
                <div class="form-group col-md-6" style="margin-top:15px;">
                  <%#= venue_form. fields_for 'opening_hour[]', opening_hour do |f| %>
                    <%#= venue_form.label :day, "#{@weekdays[i]}" %>
                    <%#= venue_form.hidden_field :day, value: "#{i}" %><br />
                    <%#= venue_form.label :opens %>
                    <%#= venue_form.text_field :open, value: "00:00:00" %>
                    <%#= venue_form.label :closes %>
                    <%#= venue_form.text_field :close, value: "00:00:00" %>
                  <%# end %>
                </div>
              </div>
            <%# end %>
          </div>
          
          <!-- HIDDEN FIELDS -->
          <%= venue_form.hidden_field :foursquare_id, :data => { :target => 'venue-autofill.fourSquareId' } %>

          <div class="field is-grouped">
            <p class="control">
              <%= venue.form_submit_button(venue_form) %>
            </p>
            <%= venue.form_delete_button %>
            <p class="control">
            <% if venue.persisted? %>
              <%= link_to "Cancel", venue_path(venue), class: "button is-light" %>
            <% else %>
              <%= link_to 'Cancel', :back, class: "button is-light" %>
            <% end %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
<% end %>