config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # DEVELOPMENT
  resources :devpages, only: :show
  
  devise_for :users, controllers: {
    # sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations'
  }
  
  get 'venues/new/venue_search', to: 'venues#venue_search'
  get '/location_search', to: 'pages#home'

  
  root to: 'pages#home'
  resources :venues do
    resources :reviews, only: [:index, :create, :new, :edit, :update, :destroy] do
      resources :photos, only: [:destroy]
    end
    resources :photos, only: [:destroy]
    get 'venue_search', on: :new
  end

  resources :cities, only: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/devpages_controller.rb
class DevpagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :show

  def show
    @venue = Venue.first
    render params[:id]
  end
end

app/views/devpages/cards.html.erb
<div id="c-card" class="column is-one-third has-text-centered">
  <%= link_to venue_path(@venue), data: { id: "#{@venue.id}"} do %>
  <section id="c-card__image" class="hero is-primary" style="<%= @venue.decorate.gradient %>, <%= @venue.decorate.hero_image_url %>">
    <div class="hero-body u-maxheight-170px">
      <div class="container">
        <h1 class="title is-6">
          <%= @venue.name %>
        </h1>
        <h1 class="subtitle is-6">
          Venue type
        </h1>
        <h1 class="subtitle is-6">
          Wifi Info
        </h1>
      </div>
    </div>
  </section>
  <div id="c-card__description" class="notification u-maxheight-170px">
    <h1 class="subtitle is-6"><%= @venue.description %></p>
    <%= raw @venue.decorate.rating_stars("1x") %>
  </div>
  <% end %>
</div>

app/views/devpages/home.html.erb
<section class="hero  is-fullheight-with-navbar  hero-image">
  <div class="hero-body">
    <div class="container  has-text-centered">
      <h1 class="title  has-text-white">
        RemoteKick
      </h1>
      <h2 class="subtitle  has-text-white">
        Remote working. On caffeine.
      </h2>
      <div class="columns">
        <div class="column is-paddingless"></div>
        <div class="column is-two-fifths">
          <div class="field has-addons">
            <p class="control is-expanded">
              <input type="text" class="input is-primary  is-rounded has-text-centered" placeholder="Search for a city">
            </p>
            <p class="control">
              <button type="submit" class="button is-rounded is-primary">Search</button>
            </p>
          </div>
        </div>
        <div class="column is-paddingless"></div>
      </div>
    </div>
  </div>
</section>

app/views/devpages/index.html.erb
<section class="section">
  <div class="container">
    <nav class="level">
      <div class="level-item">
        <div>
          <p class="heading">City</p>
          <p class="title">Melbourne</p>
        </div>
      </div>
      <div class="level-item">
        <div>
          <p class="heading">Average Wifi Speed</p>
          <p class="title">56Mbps</p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Listings on RemoteKick</p>
          <p class="title">47</p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div class="field">
          <div class="control">
            <div class="select is-primary">
              <select>
                <option>Top rated</option>
                <option>Distance</option>
                <option>Wifi Speed</option>
                <option>Price</option>
              </select>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <div class="columns">
      <!-- FILTERS -->
      <div class="column notification is-one-third">
        <!-- FILTER > LOCATION -->
        <div class="field">
          <p class="control has-icons-left">
            <input class="input" type="location" placeholder="Location" value="Melbourne">
            <span class="icon is-small is-left">
              <i class="fas fa-city"></i>
            </span>
          </p>
        </div>
        <!-- FILTER > DISTANCE -->
        <div class="field">
          <div class="control is-expanded has-icons-left">
            <div class="select is-fullwidth">
              <select>
                <option selected>Distance</option>
                <option>1 Kilometer</option>
                <option>3 Kilometers</option>
                <option>5 Kilometers</option>
                <option>10 Kilometers</option>
              </select>
            </div>
            <div class="icon is-small is-left">
              <i class="fas fa-map-marker-alt"></i>
            </div>
          </div>
        </div>
        <!-- FILTER > RATING -->
        <div class="field">
          <div class="control is-expanded has-icons-left">
            <div class="select is-fullwidth">
              <select>
                <option selected>Rating</option>
                <option>5</option>
                <option>4</option>
                <option>3</option>
                <option>2</option>
                <option>1</option>
              </select>
            </div>
            <div class="icon is-small is-left">
              <i class="fas fa-star"></i>
            </div>
          </div>
        </div>

        <!-- FILTER > PLUG SOCKETS -->
        <div class="field">
          <label class="label">Plug sockets</label>
          <div class="control">
            <label class="radio">
              <input type="radio" name="foobar">:(</label>
            <label class="radio">
              <input type="radio" name="foobar">:|</label>
            <label class="radio">
              <input type="radio" name="foobar">:)</label>
          </div>
        </div>

        <!-- FILTER > COMFORT -->
        <div class="field">
          <label class="label">Comfort</label>
          <div class="control">
            <label class="radio">
              <input type="radio" name="foobar">:(</label>
            <label class="radio">
              <input type="radio" name="foobar">:|</label>
            <label class="radio">
              <input type="radio" name="foobar">:)</label>
          </div>
        </div>

        <!-- FILTER > quietness -->
        <div class="field">
          <label class="label">Quietness</label>
          <div class="control">
            <label class="radio">
              <input type="radio" name="foobar">:(</label>
            <label class="radio">
              <input type="radio" name="foobar">:|</label>
            <label class="radio">
              <input type="radio" name="foobar">:)</label>
          </div>
        </div>

        <!-- FILTER > WIFI RESTRICTIONS -->
        <div class="field">
          <label class="checkbox">
            <input type="checkbox">Filter out venues with WiFi restrictions
          </label>
        </div>

        <div class="control">
          <button class="button is-primary">Submit</button>
        </div>
      </div>
      <div class="column notification is-secondary has-text-centered">
        <p>MAP GOES HERE</p>
        <div class="columns">
          <div class="column is-one-quarter has-text-centered">
            <img src="https://bulma.io/images/placeholders/128x128.png">
          </div>
          <div class="column is-one-quarter has-text-centered">
            <img src="https://bulma.io/images/placeholders/128x128.png">
          </div>
          <div class="column is-one-quarter has-text-centered">
            <img src="https://bulma.io/images/placeholders/128x128.png">
          </div>
          <div class="column is-one-quarter has-text-centered">
            <img src="https://bulma.io/images/placeholders/128x128.png">
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="section">
  <div class="container">
    <nav class="pagination is-rounded" role="navigation" aria-label="pagination">
      <a class="pagination-previous">Previous</a>
      <a class="pagination-next">Next page</a>
      <ul class="pagination-list">
        <li><a class="pagination-link" aria-label="Goto page 1">1</a></li>
        <li><span class="pagination-ellipsis">&hellip;</span></li>
        <li><a class="pagination-link" aria-label="Goto page 45">3</a></li>
        <li><a class="pagination-link is-current" aria-label="Page 46" aria-current="page">4</a></li>
        <li><a class="pagination-link" aria-label="Goto page 47">5</a></li>
        <li><span class="pagination-ellipsis">&hellip;</span></li>
        <li><a class="pagination-link" aria-label="Goto page 86">6</a></li>
      </ul>
    </nav>
  </div>
</section>

app/views/devpages/reviews_new.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-paddingless"></div>
      <div class="column is-two-fifths">
        <h1 class="title">Leave a review for X</h1>
          <form class="form-group col-xs-6" action="/venues" data-controller="icon-state" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="✓">

          <!-- FILTER > RATING -->
          <div class="field">
            <label class="label">Rating</label>
            <div class="control">
                <input type="radio" name="rating" id="rating_0" value="0" class="is-hidden" data-target="icon-state.input">
                <label class="c-rating-star--label" data-action="click->icon-state#selectIcons" for="rating_0"><span class="icon is-medium has-text-light" data-target="icon-state.icon"><i class="fas fa-2x fas fa-star"></i></span></label>
                <input type="radio" name="rating" id="rating_1" value="1" class="is-hidden" data-target="icon-state.input">
                <label class="c-rating-star--label" data-action="click->icon-state#selectIcons" for="rating_1"><span class="icon is-medium has-text-light" data-target="icon-state.icon"><i class="fas fa-2x fas fa-star"></i></span></label>
                <input type="radio" name="rating" id="rating_2" value="2" class="is-hidden" data-target="icon-state.input">
                <label class="c-rating-star--label" data-action="click->icon-state#selectIcons" for="rating_2"><span class="icon is-medium has-text-light" data-target="icon-state.icon"><i class="fas fa-2x fas fa-star"></i></span></label>
                <input type="radio" name="rating" id="rating_3" value="3" class="is-hidden" data-target="icon-state.input">
                <label class="c-rating-star--label" data-action="click->icon-state#selectIcons" for="rating_3"><span class="icon is-medium has-text-light" data-target="icon-state.icon"><i class="fas fa-2x fas fa-star"></i></span></label>
                <input type="radio" name="rating" id="rating_4" value="4" class="is-hidden" data-target="icon-state.input">
                <label class="c-rating-star--label" data-action="click->icon-state#selectIcons" for="rating_4"><span class="icon is-medium has-text-light" data-target="icon-state.icon"><i class="fas fa-2x fas fa-star"></i></span></label>
            </div>
          </div>
    
          <!-- FILTER > CONTENT -->
          <div class="field">
            <label class="label">Review content</label>
            <p class="control has-icons-left">
              <textarea class="textarea" placeholder="How was your experience?"></textarea>
            </p>
          </div>

          <!-- FILTER > WIFI SPEED -->
          <div class="field">
            <label class="label">Wifi Speed</label>
            <p class="control has-icons-left">
              <input placeholder="Please enter speed (Mbps)" class="input" type="number" name="wifi_speed" id="wifi_speed">
              <span class="icon is-small is-left">
                <i class="fas fa-wifi"></i>
              </span>
            </p>
          </div>

          <!-- FILTER > HAS WIFI -->
          <div class="field">
            <label class="checkbox">
              <input name="has_wifi" type="hidden" value="0"><input type="checkbox" value="1" name="has_wifi" id="has_wifi">
              This venue does not have wifi
            </label>
          </div>
      
          <!-- FILTER > PLUG SOCKETS -->
          <div class="field">
            <label class="label">Plug sockets</label>
            <div class="control">
              <input type="radio" name="plug_sockets" id="plug_sockets_0" value="0" class="is-hidden" data-target="icon-state.input">
              <label class="c-rating-star--label" data-action="click->icon-state#selectIcons" for="plug_sockets_0"><span class="icon is-medium has-text-light" for="plug_sockets" value="0" data-target="icon-state.icon"><i class="fas fa-2x fas fa-frown"></i></span></label>
              <input type="radio" name="plug_sockets" id="plug_sockets_1" value="1" class="is-hidden" data-target="icon-state.input">
              <label class="c-rating-star--label" data-action="click->icon-state#selectIcons" for="plug_sockets_1"><span class="icon is-medium has-text-light" for="plug_sockets" value="1" data-target="icon-state.icon"><i class="fas fa-2x fas fa-meh"></i></span></label>
              <input type="radio" name="plug_sockets" id="plug_sockets_2" value="2" class="is-hidden" data-target="icon-state.input">
              <label class="c-rating-star--label" data-action="click->icon-state#selectIcons" for="plug_sockets_2"><span class="icon is-medium has-text-light" for="plug_sockets" value="2" data-target="icon-state.icon"><i class="fas fa-2x fas fa-smile"></i></span></label>
            </div>
          </div>
    
          <!-- FILTER > COMFORT -->
          <div class="field">
            <label class="label">Comfort</label>
            <div class="control">
              <input type="radio" name="comfort" id="comfort_0" value="0" class="is-hidden" data-target="icon-state.input">
              <label class="c-rating-star--label" data-action="click->icon-state#selectIcons" for="comfort_0"><span class="icon is-medium has-text-light" for="comfort" value="0" data-target="icon-state.icon"><i class="fas fa-2x fas fa-frown"></i></span></label>
              <input type="radio" name="comfort" id="comfort_1" value="1" class="is-hidden" data-target="icon-state.input">
              <label class="c-rating-star--label" data-action="click->icon-state#selectIcons" for="comfort_1"><span class="icon is-medium has-text-light" for="comfort" value="1" data-target="icon-state.icon"><i class="fas fa-2x fas fa-meh"></i></span></label>
              <input type="radio" name="comfort" id="comfort_2" value="2" class="is-hidden" data-target="icon-state.input">
              <label class="c-rating-star--label" data-action="click->icon-state#selectIcons" for="comfort_2"><span class="icon is-medium has-text-light" for="comfort" value="2" data-target="icon-state.icon"><i class="fas fa-2x fas fa-smile"></i></span></label>
            </div>
          </div>
    
          <!-- FILTER > QUIETNESS -->
          <div class="field">
            <label class="label">Quietness</label>
            <div class="control">
              <input type="radio" name="quietness" id="quietness_0" value="0" class="is-hidden" data-target="icon-state.input">
              <label class="c-rating-star--label" data-action="click->icon-state#selectIcons" for="quietness_0"><span class="icon is-medium has-text-light" for="quietness" value="0" data-target="icon-state.icon"><i class="fas fa-2x fas fa-frown"></i></span></label>
              <input type="radio" name="quietness" id="quietness_1" value="1" class="is-hidden" data-target="icon-state.input">
              <label class="c-rating-star--label" data-action="click->icon-state#selectIcons" for="quietness_1"><span class="icon is-medium has-text-light" for="quietness" value="1" data-target="icon-state.icon"><i class="fas fa-2x fas fa-meh"></i></span></label>
              <input type="radio" name="quietness" id="quietness_2" value="2" class="is-hidden" data-target="icon-state.input">
              <label class="c-rating-star--label" data-action="click->icon-state#selectIcons" for="quietness_2"><span class="icon is-medium has-text-light" for="quietness" value="2" data-target="icon-state.icon"><i class="fas fa-2x fas fa-smile"></i></span></label>
            </div>
          </div>
        
          <label class="label">Please select appropriate tags</label>
          <div class="tags">
            <span class="tag">
              Serves Food
              <button class="delete is-small"></button>
            </span>
            <span class="tag">
              Open late
              <button class="delete is-small"></button>
            </span>
          </div>
    
          <div class="field is-grouped">
            <p class="control">
              <input type="submit" name="commit"class="button is-primary">
            </p>
            <p class="control">
              <a class="button is-light" href="/">Cancel</a>
            </p>
          </div>
        </form>
      </div>
      <div class="column is-paddingless"></div>
    </div>
  </div>
</section>

app/views/devpages/show.html.erb
<section class="hero is-medium is-bold hero-image">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title is-2 has-text-white">
        Primary bold title
      </h1>
      <h2 class="subtitle is-6 has-text-white">
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dicta ad est enim excepturi aliquid.
      </h2>
      <h2 class="subtitle is-6 has-text-white">
        Based on 165 reviews
      </h2>
    </div>
    <nav class="level is-mobile">
      <!-- Left side -->
      <div class="level-left">
        <div class="level-item">
          <p class="subtitle is-6 has-text-white">
            Open now
          </p>
        </div>
      </div>
    
      <!-- Right side -->
      <div class="level-right">
        <div class="level-item">
          <i class="fas fa-map-marker-alt has-text-white"></i>
          <p class="subtitle is-6 has-text-white">
            X miles away
          </p>
        </div>
      </div>
    </nav>
  </div>
</section>

<section class="section">
  <div class="container">
    <nav class="level">
      <div class="level-item">
          <div>
            <p class="heading">Wifi Speed</p>
            <p class="title">56Mbps</p>
          </div>
        </div>
      <div class="level-item">
        <div>
          <p class="heading">Price</p>
          <p class="title">
            <i class="fas fa-dollar-sign has-text-primary"></i>
            <i class="fas fa-dollar-sign has-text-primary"></i>
            <i class="fas fa-dollar-sign"></i>
          </p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Comfort</p>
          <p class="title">
            <i class="fas fa-smile has-text-primary"></i>
            <i class="fas fa-smile has-text-primary"></i>
            <i class="far fa-smile"></i>
          </p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Plug sockets</p>
          <p class="title">
            <i class="fas fa-smile has-text-primary"></i>
            <i class="fas fa-smile has-text-primary"></i>
            <i class="far fa-smile"></i>
          </p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Quietness</p>
          <p class="title">
            <i class="fas fa-smile has-text-primary"></i>
            <i class="fas fa-smile has-text-primary"></i>
            <i class="far fa-smile"></i>
          </p>
        </div>
      </div>
    </nav>
  </section>
</div>

<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column">
        <article class="media">
          <figure class="media-left">
            <p class="image is-64x64">
              <img src="https://bulma.io/images/placeholders/128x128.png">
            </p>
          </figure>
          <div class="media-content">
            <div class="field">
              <p class="control">
                <textarea class="textarea" placeholder="Add a comment..."></textarea>
              </p>
            </div>
            <div class="field">
              <p class="control">
                <button class="button">Post comment</button>
              </p>
            </div>
          </div>
        </article>
        <% 10.times do %>
        <article class="media">
          <figure class="media-left">
            <p class="image is-64x64">
              <img src="https://bulma.io/images/placeholders/128x128.png">
            </p>
          </figure>
          <div class="media-content">
            <div class="content">
              <p>
                <strong>Barbara Middleton</strong>
                <br>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis porta eros lacus, nec ultricies elit blandit non. Suspendisse pellentesque mauris sit amet dolor blandit rutrum. Nunc in tempus turpis.
                <br>
                <small><a>Like</a> · <a>Reply</a> · 3 hrs</small>
              </p>
            </div>
          </div>
        </article>
        <% end %>
      </div>
      <div class="column">
        Second column
      </div>
    </div>
  </div>
</section>

app/views/devpages/testpage.html.erb
<div class="field">
  <p class="control has-icons-left has-icons-right">
    <input autofocus="autofocus" autocomplete="email" class="input" placeholder="Email" data-target="password-validation.email" data-action="password-validation#emailEntryValidation" type="email" value="" name="user[email]" id="user_email">
    <span class="icon is-small is-left">
      <i class="fas fa-envelope"></i>
    </span>
    <span class="icon is-small is-right">
      <i class="fas fa-check"></i>
    </span>
  </p>
</div>

<div class="field">
  <p class="control has-icons-left has-icons-right">
    <input autofocus="autofocus" autocomplete="email" class="input" placeholder="Email" data-target="password-validation.email" data-action="password-validation#emailEntryValidation" type="email" value="" name="user[email]" id="user_email">
    
    <span class="icon is-small is-left">
      <i class="fas fa-envelope"></i>
    </span>
    <span class="icon is-small is-right">
      <i class="fas fa-check"></i>
    </span>
  </p>
</div>