config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # DEVELOPMENT
  resources :devpages, only: :show
  
  devise_for :users, controllers: {
    # sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations'
  }
  
  get 'venues/new/venue_search', to: 'venues#venue_search'
  get '/location_search', to: 'pages#home'

  
  root to: 'pages#home'
  resources :venues do
    resources :reviews, only: [:index, :create, :new, :edit, :update, :destroy] do
      resources :photos, only: [:destroy]
    end
    resources :photos, only: [:destroy]
    get 'venue_search', on: :new
  end

  resources :cities, only: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= render (FlashComponent.new(key: key, value: value)) %>
<% end %>

app/views/shared/_navbar.html.erb
<nav id="navbar" class="navbar is-fixed-top" role="navigation" aria-label="main navigation" data-controller="mobile-menu">
  <div class="navbar-brand">
    <%= link_to root_path do %>
      <div class="is-flex navbar-item u-h-100pc">
        <%= image_tag "logo/svg/remotekick_logo_regular.svg", class: "c-navbar__logo" %>
      </div>
    <% end %>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="mobile-menu.hamburger" data-action="mobile-menu#handleChange">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="c-navbar-links" class="navbar-menu" data-target="mobile-menu.menu">
    <div class="navbar-end">
      <% if user_signed_in? %>
        <%= link_to "Search for a listing", venues_path, id: "new_venue_link", class: "navbar-item heading is-size-6-touch" %>
        <%= link_to "Add a new listing", new_venue_path, id: "new_venue_link", class: "navbar-item heading is-size-6-touch" %>
        <%= link_to "Dashboard", "#", class: "navbar-item heading is-size-6-touch" %>
        <%= link_to "Account Settings", edit_user_registration_path, class: "navbar-item heading is-size-6-touch" %>
        <%= link_to "Log Out", destroy_user_session_path, class: "navbar-item heading is-size-6-touch", method: :delete %>
      <% else %>
        <div class="navbar-item heading is-size-6-touch">
          <%= link_to "Sign up", new_user_registration_path, class: "button is-primary u-margin-r-10px" %>
          <%= link_to "Log In", new_user_session_path, class: "button is-light" %>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_navbar_old.html.erb
<!--CHECKS TO SEE IF PAGE IS HOMEPAGE AS DEFINED IN PAGES_CONTROLLER#HOME-->
<% if @current_page == "/" %>
  <!--DISPLAYS TRANSPARENT c-navbar BY ID-->
  <div class="c-navbar c-navbar-expand-sm c-navbar-light" id="c-navbar-lewagon-transparent">
<% else %>
  <!--DISPLAYS NON-TRANSPARENT c-navbar BY ID-->
  <div class="c-navbar c-navbar-expand-sm c-navbar-light" id="c-navbar-lewagon">
<% end %>
    <%= link_to "/", class: "c-navbar-brand" do %>
      <%= image_tag "https://image.flaticon.com/icons/png/512/63/63842.png" %>
    <% end %>

    <button class="c-navbar-toggler" type="button" data-toggle="collapse" data-target="#c-navbarSupportedContent" aria-controls="c-navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="c-navbar-toggler-icon"></span>
    </button>


    <div class="collapse c-navbar-collapse" id="c-navbarSupportedContent">
      <ul class="c-navbar-nav mr-auto">
        <% if user_signed_in? %>
            <%= link_to "Add a new listing", new_venue_path, id: "new_venue_link", class: "nav-link" %>
            <%= link_to "Dashboard", "#", class: "nav-link" %>
            <%= link_to "Account Settings", edit_user_registration_path, class: "nav-link" %>
            <%= link_to "Log Out", destroy_user_session_path, class: "nav-link", method: :delete %>
        <% else %>
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
            <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
        <% end %>
      </ul>
    </div>
  </div>

  
  <!--CHECKS TO SEE IF PAGE IS HOMEPAGE AS DEFINED IN PAGES_CONTROLLER#HOME-->
  