config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # DEVELOPMENT
  resources :devpages, only: :show
  
  devise_for :users, controllers: {
    # sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations'
  }
  
  get 'venues/new/venue_search', to: 'venues#venue_search'
  get '/location_search', to: 'pages#home'

  
  root to: 'pages#home'
  resources :venues do
    resources :reviews, only: [:index, :create, :new, :edit, :update, :destroy] do
      resources :photos, only: [:destroy]
    end
    resources :photos, only: [:destroy]
    get 'venue_search', on: :new
  end

  resources :cities, only: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/venue.rb
class Venue < ApplicationRecord
  # belongs_to :user
  belongs_to :city, optional: true
  has_many :reviews, dependent: :destroy
  # belongs_to :owner, class_name: 'User', optional: true
  has_one :cover_photo, dependent: :destroy
  has_and_belongs_to_many :categories
  has_many :opening_hours
  has_one :feature_set
  has_one :address, dependent: :destroy
  has_many :photos, as: :imageable, dependent: :destroy
  has_many :venue_users, dependent: :destroy
  has_many :users, through: :venue_users
  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :photos

  validates :foursquare_id, uniqueness: true, allow_blank: true
  validates :name, presence: true
  # validates :address, presence: true
  validates_uniqueness_of :name, scope: :user_id
  # validates :description, length: { maximum: 68 }, allow_blank: true
  
  # scope :location, -> location { near(location) }
  scope :location, -> location {  where(id: Address.near(location).joins(:venue).preload(:venue).map(&:venue).map(&:id)) }
  scope :location_with_distance, -> location, distance {  where(id: Address.near(location, distance).joins(:venue).preload(:venue).map(&:venue).map(&:id)) }
  scope :rating, -> number { where("rating >= ?", number) }
  scope :upload_speed, -> number { where("round(upload_speed) >= ?", number.to_i) if number.to_i > 0 }
  scope :serves_food, -> { where(serves_food: true) }
  scope :air_conditioning, -> { where(air_conditioning: true) }
  scope :comfort, -> number { where("comfort >= ?", number) }
  scope :quietness, -> number { where("quietness >= ?", number) }
  scope :plug_sockets, -> number { where("plug_sockets >= ?", number) }
  scope :has_wifi, -> { where(has_wifi: true) }
  scope :no_wifi_restrictions, -> hours { where("wifi_restrictions < ?", hours) if hours > "0" }
  scope :has_upload_speed_data, -> { where.not(upload_speed: nil) }

  def update_values(
      review,
      attributes_to_average = [],
      attribues_to_truth_check = [],
      averaged_values = {},
      truth_checked_values = {}
    )

    # Sort attributes into seperate arrays for averaging or truth checking
    review.attributes.each do |k, val|
      attributes_to_average << k if attr_is_averageable?(k) && val != nil
      attribues_to_truth_check << [k,val] if attr_is_boolean?(k) && val != nil
    end
    
    # Recalculate averages for all averageable values which were present in review
    attributes_to_average.each do |attribute|
      averaged_values[attribute] = calculate_average(attribute)
    end

    # Assign new true/false value if the value passes truth checking
    attribues_to_truth_check.each do |boolean_key_value_pair|
      k, val = boolean_key_value_pair[0], boolean_key_value_pair[1]
      truth_checked_values[k] = truth_checked_val(k, val)
    end
    
    # Merge hashes of values to update
    updated_values = averaged_values.merge(truth_checked_values)

    # Update values
    update(updated_values)
  end

  # def to_param
  #   "#{to_global_id.to_param}-#{name.parameterize}"
  # end

  def all_photos(combined_images = [])
    photos.map { |photo| combined_images << photo }
    reviews.map { |review| review.photos.map { |photo| combined_images << photo } }
    combined_images
  end

  def featured_photo
    all_photos.find { |photo| photo.featured }
  end

  private

  def attr_is_averageable?(k)
    averageable_values = ["rating", "plug_sockets", "comfort", "quietness", "upload_speed", "download_speed", "ping"]
    averageable_values.include?(k) ? true : false
  end

  def attr_is_boolean?(k)
    boolean_values = ["serves_food", "air_conditioning", "has_wifi"]
    boolean_values.include?(k) ? true : false
  end

  def calculate_average(attribute)
    self.reviews.average(attribute.to_sym)
  end

  def truth_checked_val(attribute, value)
    # self.reviews.reload
    if self.reviews.count == 0
      nil
    # executes if there is only one review, or the last review value matches current
    elsif self.reviews.count == 1 || self.reviews[-2].send(attribute) == value
      value
    else
      # returns the previous value if it does not match the current
      self.reviews[-2].send(attribute)
    end
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  include Foursquare
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  before_action :set_venues, only: [:index]
  before_action :set_venue, only: [:show, :edit, :update, :destroy]
  before_action :venues_params, only: [:index]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user, only: [:edit, :update, :destroy]
  # @venue should be called as venue for decorated instance in views
  decorates_assigned :venue
  decorates_assigned :review
  # has_scope :location, if: :location_given?, unless: :distance_given?
  has_scope :rating
  has_scope :upload_speed
  has_scope :no_wifi_restrictions
  has_scope :comfort
  has_scope :quietness
  has_scope :plug_sockets
  has_scope :has_wifi, type: :boolean
  respond_to :html, :json
  
  def index
    # checks if venues exist for location and redirects if not
    venues_in_searched_location = @venues.location(venues_params[:location]) if location_given?
    redirect_to cities_path and return if !venues_in_searched_location.present?

    # Applies scopes
    @venues = apply_scopes(venues_in_searched_location).all
    @venues = @venues.location_with_distance(venues_params[:location], venues_params[:distance].to_i) if location_given? && distance_given?
    # @venues = @venues.near(venues_params[:location], venues_params[:distance]) if location_given? && distance_given?

    order_venues_by_param(@venues, venues_params[:order_by]) if venues_params[:order_by]

    if !request.xhr?
      set_map_markers(@venues) unless params[:order_by] 
      respond_with(@venues)
    end
  end

  def show
    @review = Review.new
    set_map_markers(@venue)
  end

  def new
    # @opening_hours = OpeningHour.new
    # @opening_hours = []
    # 7.times do
    #   @opening_hours << OpeningHour.new
    # end
    # @weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
  end

  def create
    @venue = Venue.new(venue_params)
    @address = Address.new(venue_address_params.merge(venue: @venue))
    @venue.users << current_user
    if @venue.save && @address.save
      save_photo_if_photo_uploaded(venue: @venue)
      begin
        VenueMailer.new_venue_listed(user: current_user, venue: @venue).deliver_now!
        flash[:success] = "Thank you, #{@venue.name} was successfully listed."
      rescue StandardError => e
        flash[:alert] = "#{@venue.name} was listed, but there was a problem sending an email confirmation. Please check your email."
      end
      redirect_to venue_path(@venue)
    else
      @venue.errors.messages.merge(@address.errors.messages).each_pair do |key, value|
        flash[:error] = "#{key.capitalize} #{value[0]}."
      end
      render :new
    end

    # create new opening_hour_set and assign venue
    # @opening_hour_set = OpeningHourSet.new
    # @opening_hour_set.venue = @venue
    # @opening_hour_set.save!

    # save all opening_hours and assign to opening_hour_set
    # unless opening_hours_params.empty?
    #   opening_hours_params[:opening_hour].each do |hours|
    #     new_opening_hours = OpeningHour.new(hours)
    #     new_opening_hours.opening_hour_set = @opening_hour_set
    #     new_opening_hours.save!
    #   end
    # end
  end

  def edit
  end

  def update
    @venue.address.update(venue_address_params) if params[:venue][:address_attributes].present?
    if @venue.update(venue_params)
      save_photo_if_photo_uploaded(venue: @venue)
      redirect_to venue_path(@venue)
    else
      render :edit
    end
  end

  def destroy
    redirect_to venues_path if @venue.destroy
  end

  def venue_search
    location = venue_search_params[:location]
    search = venue_search_params[:query]
    url = api_call(search, location)
    response = open(url).read
    @response_json = JSON.parse(response)
    render json: @response_json
  end

  private

  def set_venue
    @venue = Venue.find(params[:id])
  end

  def set_venues
    @venues = Venue.all
  end

  def venues_params
    params.permit(
      :location,
      :rating,
      :upload_speed,
      :comfort,
      :plug_sockets,
      :quietness,
      :has_wifi,
      :order_by,
      :distance,
      :no_wifi_restrictions,
    )
  end

  def venue_params
    params.require(:venue).permit(
      :name,
      :description,
      :serves_food,
      :air_conditioning,
      :wifi_restrictions,
      :has_wifi,
      :foursquare_id
    )
  end

  def venue_address_params
    params.require(:venue).require(:address_attributes).permit(
      :address,
      :city,
      :postcode,
      :country,
      :longitude,
      :latitude,
    )
  end

  def new_venue_photo_params
    params[:venue][:photo]
  end

  def venues_boolean_params
    params.permit(
      :serves_food,
      :air_conditioning,
      :wifi_restrictions,
      :no_wifi_restrictions,
      :has_wifi
    )
  end

  def save_photo_if_photo_uploaded(venue:)
    if new_venue_photo_params
      @photo = Photo.new(imageable: venue)
      @photo.image.attach(new_venue_photo_params[:image])
      @photo.save
    end
  end

  # def opening_hours_params
  #   # params.require([:venue, :opening_hour]).permit(:day, :open, :close)
  #   params.require(:venue).permit(opening_hour: [:day, :open, :close])
  # end

  def venue_search_params
    params.permit(:query, :location)
  end

  def set_map_markers(venues)
    @markers = []
    Array(venues).each do |venue|
      @markers << {
        lat: venue.address.latitude,
        lng: venue.address.longitude,
        infoWindow: render_to_string(partial: "venues/index_partials/index__map_cards", locals: { venue: venue })
      }
    end
  end

  def order_venues_by_param(venues, param)
    @venues = @venues.reorder("#{param} DESC NULLS LAST")
  end

  def location_given?
    venues_params[:location] && venues_params[:location] != "" && venues_params[:location] != "Everywhere"
  end

  def query_given?
    venues_params[:location] && venues_params[:location] != ""
  end

  def distance_given?
    venues_params[:distance] && venues_params[:distance].to_i > 0
  end
  
  def authorize_user
    authorize @venue
  end

  def user_not_authorized(exception)
    policy_name = exception.policy.class.to_s.underscore
 
    flash[:error] = t "#{policy_name}.#{exception.query}", scope: "pundit", default: :default

    redirect_to(venue_path(@venue))
  end
end

app/helpers/venues_helper.rb
module VenuesHelper

  def searched_location(location)
    if location && location.length > 0
      location[0] == location[0].upcase ? location : location.capitalize
    else
      "Everywhere"
    end
  end

  def average_wifi_speed(location, wifi_speeds = [])
    if location && location.length > 0
      full_results_for_location(location).each do |venue|
        wifi_speeds << venue.upload_speed if !venue.upload_speed.nil?
      end
      wifi_speeds.empty? ? "No wifi speed data" : "#{calculate_average_wifi_speed(wifi_speeds)} Mbps"
    elsif location.nil? || location == "Everywhere"
      Venue.all.each do |venue|
        wifi_speeds << venue.upload_speed if !venue.upload_speed.nil?
      end
      wifi_speeds.empty? ? "No wifi speed data" : "#{calculate_average_wifi_speed(wifi_speeds)} Mbps"
    else
      "Unknown"
    end
  end

  def total_listings_count(location)
    location && location.length > 0 ? full_results_for_location(location).count(:all) : Venue.all.count(:all)
  end

  def distance_options
    options_for_select([
      ["Distance", 0, { :data => { :target => 'set-selected-option.option', :selected => "#{params[:distance] == "0"}"}}],
      ["1 Kilometer", 1, { :data => { :target => 'set-selected-option.option', :selected => "#{params[:distance] == "1"}"}}],
      ["3 Kilometers", 3, { :data => { :target => 'set-selected-option.option', :selected => "#{params[:distance] == "3"}"}}],
      ["5 Kilometers", 5, { :data => { :target => 'set-selected-option.option', :selected => "#{params[:distance] == "5"}"}}],
      ["10 Kilometers", 10, { :data => { :target => 'set-selected-option.option', :selected => "#{params[:distance] == "10"}"}}],
    ])
  end

  def rating_options(rating_param, value)
    icon_element = content_tag( :i, nil, :class=>'fas fa-2x fas fa-star')
    span_element = content_tag( :span, icon_element, :class=>'icon is-medium has-text-light', :data => { :target => 'icon-state.icon' })
    label = label_tag( "#{rating_param}_#{value}", span_element, :class=>'c-rating-star--label', :data => { :action => 'click->icon-state#selectIcons' })
  end

  def feature_rating_options(feature_param, value)
    smile_icon = smile_type(value)
    icon_element = content_tag( :i, nil, :class=>"fas fa-2x fas fa-#{smile_icon}")
    span_element = content_tag( :span, icon_element, :class=>'icon is-medium has-text-light', :for => "#{feature_param}", :value => "#{value}", :data => { :target => 'icon-state.icon' })
    label_tag( "#{feature_param}_#{value}", span_element, :class=>'c-rating-star--label', :data => { :action => 'click->icon-state#selectIcons'})
  end

  def order_by_options
    options_for_select([
      ["Distance", { :data => { :url => "#{url_for(request.params.merge(:order_by => "distance"))}", :target => 'set-selected-option.option index-cards-ordering.option', :selected => "#{params[:order_by] == "distance"}"}}],
      ["Top rated", { :data => { :url => "#{url_for(request.params.merge(:order_by => "rating"))}", :target => 'set-selected-option.option index-cards-ordering.option', :selected => "#{params[:order_by] == "rating"}"}}],
      ["Wifi Speed", { :data => { :url => "#{url_for(request.params.merge(:order_by => "upload_speed"))}", :target => 'set-selected-option.option index-cards-ordering.option', :selected => "#{params[:order_by] == "upload_speed"}"}}],
      ["Price", { :data => { :url => "#{url_for(request.params.merge(:order_by => "price"))}", :target => 'set-selected-option.option index-cards-ordering.option', :selected => "#{params[:order_by] == "price"}"}}]
    ])
  end

  def highest_upload_speed(venues)
    if venues.length > 0 && at_least_one_value_exists(venues, "upload_speed")
      venues.reorder("upload_speed DESC NULLS LAST").first.upload_speed.ceil
    else
      0
    end
  end

  def lowest_upload_speed(venues)
    if venues.length > 0
      venues.reorder("upload_speed ASC NULLS LAST").first.upload_speed.ceil - 1
    else
      0
    end
  end

  def selected_upload_speed(venues, params_upload_speed)
    if venues.length > 0 && params_upload_speed
      params_upload_speed
    else
      0
    end
  end

  def wifi_restrictions_options
    [['Wifi Restrictions', 0], ['1 Hour', 1], ['2 Hours', 2], ['3 Hours', 3], ['4+ Hours', 4]]
  end

  private

  def smile_type(value)
    case value
    when 0
      "frown"
    when 1
      "meh"
    when 2
      "smile"
    end
  end

  def at_least_one_value_exists(venues, attribute)
    venues.any? {|venue| venue.send(attribute).is_a?(Float)}
  end

  def calculate_average_wifi_speed(wifi_speeds)
    (wifi_speeds.sum / wifi_speeds.length).round(2)
  end

  def full_results_for_location(location)
    Venue.location(location)
  end
end

app/views/venues/show_partials/_mobile_navigation_show.html.erb
<nav class="navbar is-fixed-bottom is-hidden-desktop level is-mobile has-background-dark is-fixed-bottom is-marginless u-bottom-minus-1px">
  <div class="level-item has-text-centered">
    <div id="mobile-filters-button" class="level-item has-text-white has-text-centered" data-element="indexFilters" data-action="click->mobile-index-navigation#handleClick">
      <i class="fas fa-sliders-h"></i>
    </div>
    <div data-element="map" data-action="click->mobile-index-navigation#handleClick">
      <p class="heading has-text-white is-size-6">Map</p>
    </div>
  </div>
  <div class="level-item has-text-centered">
    <div data-element="venuesList" data-action="click->mobile-index-navigation#handleClick">
      <p class="heading has-text-white is-size-6">List</p>
    </div>
  </div>
</nav>

app/views/venues/show_partials/_review_media_item.html.erb
<article class="media">
  <%= render(AvatarComponent.new(user: review.user, type: "media_object")) %>
  <div class="media-content">
    <div class="content">
      <strong><%= review.user.first_name %></strong><br>
      <span class="has-text-primary">
        <%= raw review.rating_stars("1x") %>
      </span><br>
      <%= review.content %>
      <div class="columns is-multiline">
        <% if review.photos.any? %>
        <% review.photos.each do |photo| %>
        <div class="column is-one-quarter">
          <div class="image is-square c-photo-thumbnail">
            <%= image_tag photo.image, class: "u-object-fit" %>
          </div>
        </div>
        <% end %>
        <% end %>
      </div>

      <small>
        <% if policy(review).update? %>
        <%= link_to "Edit", edit_venue_review_path(venue, review) %>
        ·
        <%= link_to "Delete", venue_review_path(venue, review), method: :delete %>
        ·
        <% end %>
        <!-- <a>Like</a>
        ·
        <a>Reply</a>
        · -->
        <%= review.when_reviewed %>
      </small>
    </div>
  </div>
</article>

app/views/venues/show_partials/_show__feature_bar.html.erb
<section class="section">
  <div class="container">
    <nav class="level">
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Wifi Speed</p>
          <p class="title is-size-5-touch	title is-size-4-desktop"><%= venue.wifi_speed %></p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Price</p>
          <p class="title is-size-5-touch	title is-size-4-desktop">
            <i class="fas fa-dollar-sign has-text-primary"></i>
            <i class="fas fa-dollar-sign has-text-primary"></i>
            <i class="fas fa-dollar-sign"></i>
          </p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div class="h-80pc">
          <p class="heading">Comfort</p>
          <p class="title is-size-5-touch	title is-size-4-desktop">
            <%= raw venue.display_icons("comfort") %>
          </p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div class="h-80pc">
          <p class="heading">Plug sockets</p>
          <p class="title is-size-5-touch	title is-size-4-desktop">
            <%= raw venue.display_icons("plug_sockets") %>
          </p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div class="h-80pc">
          <p class="heading">Quietness</p>
          <p class="title is-size-5-touch	title is-size-4-desktop">
            <%= raw venue.display_icons("quietness") %>
          </p>
        </div>
      </div>
    </nav>
  </div>
</section>

app/views/venues/show_partials/_show__hero_section.html.erb
<section id="c-venues-show-hero-section" class="hero is-medium is-bold" style="<%= venue.gradient %>, <%= venue.decorate.hero_image_url(venue.featured_photo ? url_for(venue.featured_photo.image) : nil) %>">
  <div class="hero-body">
  <% if policy(venue).update? %>
    <%= link_to edit_venue_path(venue) do %>
      <button class="button c-venue-edit-button">
        <span class="icon">
          <i class="fas fa-edit"></i>
        </span>
        <span>Edit Details</span>
      </button>
    <% end %>
  <% end %>
    <div class="container has-text-centered">
      <h1 class="title is-2 has-text-white has-text-shadow">
        <%= venue.name %>
      </h1>
      <h2 class="subtitle is-6 has-text-white has-text-shadow">
        <%= venue.description %>
      </h2>
      <span class="icon is-medium has-text-light has-text-shadow">
        <%= raw venue.rating_stars("2x") %>
      </span>
      <h2 class="subtitle is-6 has-text-white has-text-shadow">
        <%= venue.reviews_info_text %>
      </h2>
    </div>
    <nav class="level is-mobile">
      <!-- Left side -->
      <div class="level-left">
        <div class="level-item">
          <i class="fas fa-door-open has-text-white"></i>
          <p class="subtitle is-6 has-text-white has-text-shadow">
            Open now
          </p>
        </div>
      </div>
    
      <!-- Right side -->
      <div class="level-right">
        <div class="level-item">
          <i class="fas fa-map-marker-alt has-text-white"></i>
          <p class="subtitle is-6 has-text-white">
            X miles away
          </p>
        </div>
      </div>
    </nav>
    
    <nav class="level is-mobile">
      <!-- Left side -->
      <div class="level-left">
        <div class="level-item">
        <% if venue.wifi_restrictions.positive? %>
          <i class="fas fa-stopwatch has-text-white"></i>
          <p class="subtitle is-6 has-text-white has-text-shadow">
            Venue has wifi restrictions.
          </p>
        <% else %>
          <i class="fas fa-check-circle has-text-white"></i>
          <p class="subtitle is-6 has-text-white has-text-shadow">
            Venue does not have wifi restrictions.
          </p>
        <% end %>
        </div>
      </div>
    
      <!-- Right side -->
      <div class="level-right">
      </div>
    </nav>
  </div>
</section>

app/views/venues/show_partials/_show__lower_section.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column">
        <% if policy(review).new?(@venue) %>
          <%= render "venues/show_partials/show__new_review_quickform", venue: @venue, review: review %>
        <% end %>
        <% @venue.reviews.order('updated_at DESC').each do |review| %>
          <%= render partial: "venues/show_partials/review_media_item", locals: { review: review.decorate } %>
        <% end %>
      </div>
      <div class="column">
        <!-- Second column -->
      </div>
    </div>
  </div>
</section>

app/views/venues/show_partials/_show__map.html.erb
<div class="section" data-section-id="map" data-target="tabs.contentSection">
  <div class="container">
    <%= render 'venues/shared_partials/map' %>
  </div>
</div>

app/views/venues/show_partials/_show__new_review_quickform.html.erb
<%= form_with model: [venue, review], local: true, class: "form-group col-xs-6" do |review_form| %>
  <article class="media">
    <%#= render(MediaObjectComponent.new(user: current_user)) %>
    <%= render(AvatarComponent.new(user: current_user, type: "media_object")) %>
    <%= render(MediaObjectContentFormComponent.new(review_form: review_form)) %>
  </article>
<% end %>

app/views/venues/show_partials/_show__reviews.erb
<section class="section is-hidden" data-section-id="reviews" data-target="tabs.contentSection">
  <div class="container">
    <div class="columns">
      <div class="column">
        <% if policy(review).new?(@venue) %>
          <%= render "venues/show_partials/show__new_review_quickform", venue: @venue, review: review %>
        <% end %>
        <% @venue.reviews.order('updated_at DESC').each do |review| %>
          <%= render partial: "venues/show_partials/review_media_item", locals: { review: review.decorate } %>
        <% end %>
      </div>
      <div class="column">
        <!-- Second column -->
      </div>
    </div>
  </div>
</section>

app/views/venues/show_partials/_show__tabs.html.erb
<div class="tabs is-centered">
  <ul>
    <%= render(TabComponent.new(tab: "Map", icon_name: "map-marked-alt")) %>
    <%= render(TabComponent.new(tab: "Reviews", icon_name: "comments")) %>
  </ul>
</div>